spring:
  application:
    name: dubbo-provider
server:
  port: 9000
  servlet:
    context-path: /api/dubbo/provider
dubbo:
  application:
    name: ${spring.application.name}
  basePackages: com.example.demo.manage
  registry:
    address: zookeeper://127.0.0.1:2181
  protocal:
    name: dubbo
    port: -1 #随机端口